export const RESET_BOOK = "RESET_BOOK"
export const RESET_BOOK_SUCCESS = "RESET_BOOK_SUCCESS"

export const ADD_COUNT_AUTO = "ADD_COUNT_AUTO"
export const ADD_COUNT_AUTO_SUCCESS = "ADD_COUNT_AUTO_SUCCESS"

export const UPDATE_COUNT = "UPDATE_COUNT"
export const UPDATE_COUNT_SUCCESS = "UPDATE_COUNT_SUCCESS"
