export const GET_BOOK = "GET_BOOK"
export const GET_BOOK_SUCCESS = "GET_BOOK_SUCCESS"
export const GET_BOOK_LOADING = "GET_BOOK_LOADING"
export const GET_BOOK_FAIL = "GET_BOOK_FAIL"

export const RESET = "RESET"
export const RESET_SUCCESS = "RESET_SUCCESS"

export const ADD_BOOK_PAGE = "ADD_BOOK_PAGE"
export const ADD_BOOK_PAGE_SUCCESS = "ADD_BOOK_PAGE_SUCCESS"
export const ADD_BOOK_PAGE_FAIL = "ADD_BOOK_PAGE_FAIL"
export const ADD_BOOK_PAGE_LOADING = "ADD_BOOK_PAGE_LOADING"
