export const GET_USER = "GET_USER"
export const GET_USER_SUCCESS = "GET_USER_SUCCESS"
export const GET_USER_FAIL = "GET_USER_FAIL"

export const RESET_USER = "RESET_USER"
export const RESET_USER_SUCCESS = "RESET_USER_SUCCESS"